spring:
  application:
    name: eurekaserver
  security:
    user:
      name: eureka-user-course
      password: eru-reuesrkeauo-sc

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false